### ISSUE TITLE
Clutter-CRITICAL - A lot of errors in journal

### ISSUE THREAD

**Issue by nogo** [elvetemedve/gnome-shell-extension-system-monitor#1]
I have a lot of errors like these in my journal: gnome-shell:(779): Clutter-CRITICAL **: clutter_text_get_text: assertion 'CLUTTER_IS_TEXT (self)' failed

Linux: Arch x64
Gnome: 3.20

**Comment by elvetemedve** [comment]
@nogo Thanks for reporting this problem.
It is already fixed in version 1.0.1 and the code is submitted for review.

**Comment by nogo** [comment]
Thanks. :)

**Comment by elvetemedve** [comment]
@nogo Now you should see that an update is available for the extension. Can you please update it and check if errors have gone?

**Comment by nogo** [comment]
great, seems to work now, thanks
