### ISSUE TITLE
GNOME 47 support

### ISSUE THREAD

**Issue by bhuvankrishna** [elvetemedve/gnome-shell-extension-system-monitor#102]
It looks like the extension breaks for GNOME 47. I tried to install it from extensions.gnome.org but it say's incompatible version. Hope it is a minor change to get the extension supported for 47. I tried it on Archlinux with GNOME 47. I really like the extension a lot it gives a quick glimpse into my systems state. Thank you for creating it and supporting it.

**Comment by elvetemedve** [comment]
Hi @bhuvankrishna,

Thanks for the feedback. I'm glad you found it useful.

This time they removed a Color management utility which was used by indicators sitting on the top menu. I've replaced that with a custom solution, which made the extension loading again. 

I released a new version (you should get it automatically), which should be compatible with Gnome Shell 47.
If you still see compatibility issues, feel free to share it here.

**Comment by bhuvankrishna** [comment]
Thank you so @elvetemedve for the update. I got the new version and it is working as expected. Thanks again.
