### ISSUE TITLE
Where did the Graphs go?

### ISSUE THREAD

**Issue by alwinmark** [elvetemedve/gnome-shell-extension-system-monitor#15]
Hi,

I'm pretty sure I had this Extension once or at least one similar to this. But with that extension I had graphs instead these colored Icons, which I would prefer. 

Did you change this, or was it another extension? Could you add at least Graphs in the detail view?

Thanks

**Comment by elvetemedve** [comment]
Hi,

You are talking about a different extension. It's like this from the beginning.

I don't have time for this, sorry.
