### ISSUE TITLE
Preferences: Unclear UI: What does the "General" button do?

### ISSUE THREAD

**Issue by genodeftest** [elvetemedve/gnome-shell-extension-system-monitor#16]
It seems like the "General" button is part of a GtkStackSwitcher. How about 
a) not showing the stack switcher in case there is only one stack element
b) showing some info how to make "System Monitor" show more information how to get more configuration options

**Comment by elvetemedve** [comment]
b) What do you mean? There is no option to show more info, only to show less, by turning off indicators.

**Comment by genodeftest** [comment]
I don't understand. There is a single page called "General". Could there be a second page? If yes, what do I need to do to make it visible? If no, why is there a "General" button when there is no other choice?

**Comment by genodeftest** [comment]
Ok, now (with the latest version) I see two alternative sections, "General" and "Memory". This sounds more intuitive to me.
