### ISSUE TITLE
no network activity

### ISSUE THREAD

**Issue by anika200** [elvetemedve/gnome-shell-extension-system-monitor#2]
Not sure what I need or how to fix my network monitor suddenly quit working. I think it happened as a result of the new update I did on 6/6/16 but I had system updates that day too..??
How can it be fixed?

**Comment by elvetemedve** [comment]
@anika200 Can you take a look at the error logs, which could give some hint where to look for the issue?

In the Gnome desktop session press `Alt + F2` and type the `lg` command. Now select the **Extensions** tab on the top right corner. Scroll down to the **Network Monitor** entry and click on the **Show Errors**. 
What do you see there?

**Comment by anika200** [comment]
No errors there, my bad though it seems to be working fine today. I have no idea what was wrong, consider the problem solved. Thank you for the great extension and taking the time to respond.
