### ISSUE TITLE
Error loading extension on Ubuntu Gnome 16.04

### ISSUE THREAD

**Issue by cm-s** [elvetemedve/gnome-shell-extension-system-monitor#20]
I have built the extension under `/tmp` and loaded it via gnome-tweak-tool, but I won't load. This is the second time I've installed it. The first time I moved the zip into the downloads folder before loading it, though nothing happened, even after restarting. Might there be a permissions issue?

**Comment by elvetemedve** [comment]
Tweak tool will extract the ZIP into the `~/.local/share/gnome-shell/extensions/System_Monitor@bghome.gmail.com/` directory. Make sure that it's writable. One you have the files there, restart the Gnome Shell.

**Comment by cm-s** [comment]
I see, my extensions weren't writable to others (drwxrwxr-x).  Your solution worked. Thank you, it looks much more minimalistic than my other system monitoring extension.
