### ISSUE TITLE
Newer version of the extension popup repeatedly appears

### ISSUE THREAD

**Issue by cono** [elvetemedve/gnome-shell-extension-system-monitor#21]
Hi,

I have issue installing this extension from google-chrome, so I used instruction from README and made it manually.
But after that looks like there some issue with tracking version and "Update available" popup appears for me all the time.

Let me know what information I can provide or at least where to look. Probably it needs to be registered somewhere else as it was installed not via chrome-gnome-shell.

**Comment by elvetemedve** [comment]
Hi @cono,

I don't see an available update when I open https://extensions.gnome.org/local/ in Chrome.

There is one thing I can think of. Version is stored in `~/.local/share/gnome-shell/extensions/System_Monitor@bghome.gmail.com/metadata.json`, but every time a new version is uploaded to **extensions.gnome.org**, it will replace the version to an integer (currently it's 5), basically ignoring the version from the author.

Try to update the version and check it out in Chrome again:
```bash
sed -i 's/"version":.*/"version": "5"/' ~/.local/share/gnome-shell/extensions/System_Monitor@bghome.gmail.com/metadata.json
```

**Comment by cono** [comment]
Here is the thing that when I go to extensions.gnome.org/local I don't see it either, but popup appears anyway. And when I press on it, it moves me to extensions.gnome.org/local with no ability to upgrade.

Let me try to change this to 5, I need some time to check if popup appears after the change.
Thanks for the suggestion!

**Comment by cono** [comment]
Yes, _"version": 5_ works fine.

Would you mind to change your versioning system to the gnome-shell one?

**Comment by elvetemedve** [comment]
Yes, it looks like I have no other choice.

Developing a Gnome extension becomes not much fun to me. :-( 
API documentation is not so good, basically C libraries are documented, but extensions are written in Javascript. Run-time errors are cryptic, it's hard to guess what went wrong and where. Supporting multiple Gnome versions means running older distributions in a virtual machine. Builder, the Gnome IDE is still under heavy development, currently not supporting extension development.

**Comment by cono** [comment]
Oh man, I feel your pain :)
I would suggest to support only 2 latest versions of gnome, don't see any reason to support older ones.
Thanks for help! Awesome support! :)
