### ISSUE TITLE
Display RES memory instead of VIRT?

### ISSUE THREAD

**Issue by bagage** [elvetemedve/gnome-shell-extension-system-monitor#25]
It seems that the extension currently shows the virtual size of processes. 
I expected it to show how much processes were using physical memory instead (RES column from `htop`). 
Is that the intended behavior?

**Comment by elvetemedve** [comment]
@bagage Processes are sorted by the sum of virtual memory + resident memory + shared memory. The intention was to accumulate all memory usage. `htop` [shows the resident memory](https://github.com/hishamhm/htop/blob/master/Process.c#L419) in that column. 
Do you think it would make more sense to use resident memory only? Or make it configurable in settings?

**Comment by bagage** [comment]
@elvetemedve Yes I think only resident memory is useful - at least for me. I don't know if everyone would agree with that however (including you!), so some setting could be just fine.
But I really tend to think that people would expect to see what "actual physical memory" is being used by apps, not all the virtual one. WDYT?

**Comment by elvetemedve** [comment]
As for me a tool like system monitor is useful in situations, when one of the running program is misbehaving. In such a case I expect a system monitor to help me easily find the source of the problem. 
For example show me the process that allocated all available memory. Probably it's enough to watch RAM in most cases, but I'm not sure it covers all failure scenarios.

**Comment by bagage** [comment]
Yeah OK it makes sense. Maybe a setting would be great then, so that each can see what he/she would expect to see? To clarify: I personally use your great extension as a watchdog - when my computer becomes really slow, I'd like to kill immediately the culprit before it starts to swap&die. Generally this culprit is eating all the RAM with some infinite loop or similar (and is generally me :)).

**Comment by elvetemedve** [comment]
I see. I will try to make this change during the weekend.

**Comment by elvetemedve** [comment]
@bagage I've changed the memory calculation. Could you test the new version, before I make a new release?
Here is the new version:
[System_Monitor@bghome.gmail.com-6.zip](https://github.com/elvetemedve/gnome-shell-extension-system-monitor/files/769498/System_Monitor.bghome.gmail.com-6.zip)

**Comment by bagage** [comment]
Great news! It seems that it works as expected; at least it is consistent with `htop`! Good job @elvetemedve.

**Comment by elvetemedve** [comment]
Excellent. Then I'll release it.
Thanks for the feedback.

**Comment by elvetemedve** [comment]
New version has been released.
