### ISSUE TITLE
There is an error if you want to install it after another same profile extension.

### ISSUE THREAD

**Issue by ebola-dc** [elvetemedve/gnome-shell-extension-system-monitor#32]
Hello!

I had some problems with your extension as after the fresh installation the extension web page just showed me a pink error. After a dbus-monitor investigation I got that the problem source was that I used another tool for such goal.

The other extension is:
https://extensions.gnome.org/extension/120/system-monitor/

The dbus error was something like name duplication error or so. After I removed the other extension the problem solved. Currently I can already use yours.

The interesting part of it is when I install the another one firstly and just then your one I got an error on the extensions page. BUT! in case if I install your firstly and then the other the problem is not appear. In this case both of the extensions work smoothly.

Please try to solve it if possible to save some time to the your future users:)

Thanks for it and of course lot of thanks completly for the extension as I love it!

**Comment by elvetemedve** [comment]
Hi @ebola-dc,

Thanks for reporting this error.
As far as I know Gnome Shell extensions are identified by an UUID value which is different between the two extensions. See the [other extension](https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet/blob/master/system-monitor%40paradoxxx.zero.gmail.com/metadata.json#L3) and [this one](https://github.com/elvetemedve/gnome-shell-extension-system-monitor/blob/master/System_Monitor%40bghome.gmail.com/metadata.json#L3). However the name is basically the same (**system-monitor** vs. **System Monitor**). 
I will investigate what's going on.

**Comment by ebola-dc** [comment]
Nagyon köszönöm:)

(Thank you very much!)

**Comment by elvetemedve** [comment]
@ebola-dc  Megteszem, ami tőlem telik. :)

It looks like both extensions used the **system-monitor** string as a unique identifier for registering the indicator widget on the top panel. See the [other extension](https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet/blob/master/system-monitor%40paradoxxx.zero.gmail.com/extension.js#L1941) and [this one](https://github.com/elvetemedve/gnome-shell-extension-system-monitor/blob/master/System_Monitor%40bghome.gmail.com/view.js#L47).

I'll fix this by changing the ID to the extension UUID which is guaranteed to be unique.

**Comment by ebola-dc** [comment]
Thanks for your effort!

**Comment by elvetemedve** [comment]
[The fix](https://github.com/elvetemedve/gnome-shell-extension-system-monitor/releases/tag/10) has been released.
