### ISSUE TITLE
Display is too wide for 1366x768

### ISSUE THREAD

**Issue by da0ist** [elvetemedve/gnome-shell-extension-system-monitor#41]
1366x768 is the maximum resolution several of my ThinkPads. This is what I see:

![screenshot from 2017-11-06 13-13-40](https://user-images.githubusercontent.com/7945846/32461813-56c58234-c2f4-11e7-933f-6c79734674b4.png)

**Comment by elvetemedve** [comment]
It's a duplicate of https://github.com/elvetemedve/gnome-shell-extension-system-monitor/issues/10.

**Comment by da0ist** [comment]
It's a duplicate of #10.
