### ISSUE TITLE
The names of the processes are not truncated

### ISSUE THREAD

**Issue by zianglei** [elvetemedve/gnome-shell-extension-system-monitor#52]
My laptop's screen resolution is 1366x768, and when I open the CPU indicator, some of the content is off the screen

I think the reason is that the names of the processes which have long names are not truncated.

Thank you

PS: I tried to upload the screenshot but the network is ****, sorry for that

**Comment by zianglei** [comment]
![](http://p3jggzq4i.bkt.clouddn.com/Screenshot)

**Comment by elvetemedve** [comment]
Nice catch. I'll try to figure out something.
