### ISSUE TITLE
Popup category icons disappeared

### ISSUE THREAD

**Issue by AbdElraoufSabri** [elvetemedve/gnome-shell-extension-system-monitor#53]
It was working perfectly but suddenly the icons disappeared

![screenshot from 2018-09-13 18-35-13](https://user-images.githubusercontent.com/11881564/45502255-d1027c80-b783-11e8-9114-5c6b70e09682.png)

-> uninstalled && reinstalled but in vain

**Comment by elvetemedve** [comment]
Thanks for reporting this issue. Looks like the last release would have required more testing.

**Comment by elvetemedve** [comment]
Fixed in version 14.
