### ISSUE TITLE
Gnome 3.32 support

### ISSUE THREAD

**Issue by alexandru-calinoiu** [elvetemedve/gnome-shell-extension-system-monitor#56]
Any chance to support the latest gnome version?

Looking at the logs it seems the error is:

```
xtension "System_Monitor@bghome.gmail.com" had error: TypeError: this._construct is not a function
```

**Comment by lfelipe1501** [comment]
yes please support Gnome 3.32

**Comment by elvetemedve** [comment]
I will try to look into that this week.

**Comment by mon0theist** [comment]
Can confirm, needs update for GNOME 3.32

**Comment by mon0theist** [comment]
Not sure if this helps, saw this on another extension that was broken by the 3.32 update:

"GNOME Shell 3.32 removed Lang.class() and we should be using ES6 classes instead. See https://gitlab.gnome.org/GNOME/gnome-shell/merge_requests/361"

**Comment by elvetemedve** [comment]
@mon0theist Thanks, that helps. I already eliminated depending on the `Lang` class in the code. But there are other changes that break the functionality. So it needs more work. :(

**Comment by bararchy** [comment]
@elvetemedve Not sure if needed but I'm also following and need an update :)

**Comment by dino99** [comment]
job already done, and works as expected:
https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet/pull/510

**Comment by mrksngl** [comment]
@dino99 not sure if I mess something up here, but I think this is another monitor applet.

**Comment by elvetemedve** [comment]
This is now fixed in [Version 15](https://github.com/elvetemedve/gnome-shell-extension-system-monitor/releases/tag/15). It will be released at extensions.gnome.org soon.
