### ISSUE TITLE
it doesn't work in gnome 3.28.4 Error: Requiring GTop, version none: Typelib file for namespace 'GTop' (any version) not found

### ISSUE THREAD

**Issue by MeepoAII** [elvetemedve/gnome-shell-extension-system-monitor#61]
Hello,  I want to use System-monitor in my ubuntu18.04, and my gnome-shell version is 3.28.4, I get the error messages as follows:
`gnome-shell[1796]: Extension "System_Monitor@bghome.gmail.com" had error: Error: Requiring GTop, version none: Typelib file for namespace 'GTop' (any version) not found`

I' ve looked around and it seems nobody get the exact same problem with me.

and what can i do for this problem?
Thanks in advance!

and i reinstall it, there is more messages:

`Some code accessed the property 'ENABLED_EXTENSIONS_KEY' on the module 'extensionSystem'. That property was defined with 'let' or 'const' inside the module. This
Extension "System_Monitor@bghome.gmail.com" had error: Error: Requiring GTop, version none: Typelib file for namespace 'GTop' (any version) not found 
org.gnome.Shell.desktop[5578]: [5686:5704:0807/133206.344132:ERROR:socket_stream.cc(219)] Closing stream with result -2`

**Comment by elvetemedve** [comment]
Hi @MeepoAII,

That's because the extension requires an external library called Libgtop. Check out [the installation guide](https://github.com/elvetemedve/gnome-shell-extension-system-monitor/wiki/Installation#dependencies) how to get that on Ubuntu.
