### ISSUE TITLE
GNOME 3.34 support

### ISSUE THREAD

**Issue by feimosi** [elvetemedve/gnome-shell-extension-system-monitor#62]
First of all, I love this extension, you've done really great job. Unfortunately after recent upgrade to GNOME 3.34 it stopped working, any chance of adding support for the latest GNOME? I can only imagine how annoying it is with their constantly changing API as every update breaks half of my extensions...

**Comment by elvetemedve** [comment]
Hi @feimosi, 

Thanks for the feedback. I'm also grad that you found this extension useful.

I plan to review the changes soon and make it compatible with the latest release. 
Unfortunately GNOME development is terrible from an outsider point of view like myself. There is no easy way to test the extension in advance before a new release. I spent few hours to build Gnome from sources, but I gave up in the end. Another way would be running the next Gnome beta in a virtual machine. In additon to that they don't provide an API for Shell extensions, which means you can do anything you want in Javascript. Last time they had upgraded the Javascript/ECMA script version which led to broken code again.
So I decided to maintain the code, but stop adding new features or improvements. Rumors goes around Gnome 4 will get a significantly different software architecture compared to 3, meaning all extensions have to be re-created from scratch.

**Comment by krashekspres** [comment]
If it helps:
```
Oct 03 11:01:47 traken gnome-shell[1858]: Usage of object.actor is deprecated for Menu
                                          get@resource:///org/gnome/shell/ui/environment.js:235:29
                                          _init@/var/home/dario/.local/share/gnome-shell/extensions/System_Monitor@bghome.gmail.com/view.js:28:9
                                          enable@/var/home/dario/.local/share/gnome-shell/extensions/System_Monitor@bghome.gmail.com/extension.js:51:16
                                          _callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:130:13
                                          loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:263:21
                                          callback@resource:///org/gnome/shell/ui/extensionDownloader.js:231:17
                                          gotExtensionZipFile/<@resource:///org/gnome/shell/ui/extensionDownloader.js:99:13
Oct 03 11:01:47 traken gnome-shell[1858]: Extension "System_Monitor@bghome.gmail.com" had error: TypeError: this.setIcon is not a function
```

**Comment by elvetemedve** [comment]
I don't have much free time nowadays, but will try to find a space for fixing that.

**Comment by Austaras** [comment]
@elvetemedve I agree that overall gnome shell extension development experience is awful but this extension just need a easy fix. You only need to change `BaseMenuItem` and all its subclass from es6 class to GoObject class and it'll work fine

**Comment by elvetemedve** [comment]
I have prepared a [new release](https://github.com/elvetemedve/gnome-shell-extension-system-monitor/releases/tag/untagged-c6b8dbc3331d0508db2e) for fixing this issue. It's under code review now.

**Comment by elvetemedve** [comment]
The release went live.

**Comment by alexykot** [comment]
Just tried installing the new version, and it still fails for me. Arch Linux, Gnome 3.34.1. I'm not sure how to debug Gnome extensions, but LookingGlass to [this SO](https://stackoverflow.com/questions/8425616/how-to-test-debug-gnome-shell-extensions-is-there-any-tool-for-that?answertab=votes#tab-top) shows following error:

`TypeError: this.setIcon is not a function.`

**Comment by elvetemedve** [comment]
Hi @alexykot,
That's one of the error that this new release should fix. Probably the extension is not reloaded properly. Under Xorg session you can reload the Shell by Pressing `Alt + F2` and enter the `r` (restart) command and run it. That will restart Gnome Shell and reload the extension. Under Wayland session you have to log out and log in again to restart it.

**Comment by rawlink** [comment]
I used the `Alt + F2` and `r` command @elvetemedve  suggested and that fixed for me. Thanks so much! I love this extension.

**Comment by alexykot** [comment]
Worked for me after session restart. 
Also, did the UI design change between this and earlier version? I no longer have the mini-charts in the status bar at the top (or was it another extension?).

**Comment by elvetemedve** [comment]
@alexykot This extension never did that.
