### ISSUE TITLE
Gnome 3.36 support

### ISSUE THREAD

**Issue by ericdallo** [elvetemedve/gnome-shell-extension-system-monitor#66]
Thanks for the awesome project, could you add support for gnome 3.36?

**Comment by elvetemedve** [comment]
Hi @ericdallo,

Thanks for the feedback. The latest release ([version 18](https://github.com/elvetemedve/gnome-shell-extension-system-monitor/releases/tag/18)) is compatible with Gnome Shell 3.36. Maybe the only problem is that not marked as compatible in [metadata](https://github.com/elvetemedve/gnome-shell-extension-system-monitor/blob/master/System_Monitor%40bghome.gmail.com/metadata.json#L2) file.

What's the exact problem you have?

**Comment by ericdallo** [comment]
Oh sorry, I use NixOS and I tought the problem is in your extension, but the problem is in the derivation recipe [here](https://github.com/NixOS/nixpkgs/blob/master/pkgs/desktops/gnome-3/extensions/system-monitor/default.nix)... I'll open a PR on nixpkgs to fix it. Thank you!

**Comment by elvetemedve** [comment]
Actually that package wraps up another system monitor extension, not this one.
But never mind. I'm glad that no changes needed here. :)

**Comment by ericdallo** [comment]
Oh my, Sorry about that :sweat_smile:
