### ISSUE TITLE
Gnome 3.40 support

### ISSUE THREAD

**Issue by feimosi** [elvetemedve/gnome-shell-extension-system-monitor#72]
Any chance of adding Gnome 3.40 support? It's a really great extension.

**Comment by elvetemedve** [comment]
Hi @feimosi,

Yes, it's on the way. :)

**Comment by elvetemedve** [comment]
https://github.com/elvetemedve/gnome-shell-extension-system-monitor/releases/tag/20

**Comment by feimosi** [comment]
Awesome, thanks a lot! :rocket:
