### ISSUE TITLE
Put a color to the whole icon, not part of it

### ISSUE THREAD

**Issue by ai** [elvetemedve/gnome-shell-extension-system-monitor#75]
CPU and memory icons has a color part in the center, but part of the icon always gray.

![20210506120447](https://user-images.githubusercontent.com/19343/117330022-43f42080-ae63-11eb-9450-e67c30457668.png)

I think using a full color icon (like we have in network color) will improve icon readability.

**Comment by elvetemedve** [comment]
Actually that's a good point. Those two are custom SVG icons, while the others come with Gnome by default. Coloring is done via CSS, so the same style is applied to all of these. Probably the objects in the custom SVGs differ somehow. It needs  investigation to find the difference and a way to fix this.

**Comment by ai** [comment]
Maybe we need to change not only `fill` but also `stroke` (border color) in CSS for SVG?

**Comment by ai** [comment]
Fixed by https://github.com/elvetemedve/gnome-shell-extension-system-monitor/pull/76
