### ISSUE TITLE
Do not match GNOME System Monitor

### ISSUE THREAD

**Issue by ai** [elvetemedve/gnome-shell-extension-system-monitor#77]
Fedora 33. I started all application to have `out of the memory` (for both RAM and swap) in GNOME System Monitor but extension shown only 39%.

![Screenshot from 2021-05-08 00-51-38](https://user-images.githubusercontent.com/19343/117527181-10ff7900-af98-11eb-823c-d65847e38c8c.png)

**Comment by elvetemedve** [comment]
Hi @ai,

Calculating the RAM usage is not trivial as Linux kernel accounting does not provide a single value as "used RAM", but usage is split across categories. You can see how Linux tracks memory allocation by running `cat /proc/meminfo`. The extension implemented the same formula for calculating RAM usage as the `htop` application which looks like this:

https://github.com/elvetemedve/gnome-shell-extension-system-monitor/blob/master/System_Monitor%40bghome.gmail.com/meter.js#L278-L279

Gnome's System Monitor must use a different formula I suppose.

I don't have information about which calculation method is the correct/official.

**Comment by ai** [comment]
Fixed in https://github.com/elvetemedve/gnome-shell-extension-system-monitor/pull/78
