### ISSUE TITLE
Gnome Shell 43 support

### ISSUE THREAD

**Issue by tukanos** [elvetemedve/gnome-shell-extension-system-monitor#86]
Could you please add Gnome Shell 43 support?

**Comment by farlydetrias2022** [comment]
edit metadata.json in $HOME/.local/share/gnome-shell/extensions/System_Monitor@bghome.gmail.com 
and add "43" like this, restart gnome

"shell-version": [
    "3.34",
    "3.32",
    "3.38",
    "40.0",
    "41",
    "42",
    "43"

**Comment by tukanos** [comment]
> edit metadata.json in $HOME/.local/share/gnome-shell/extensions/[System_Monitor@bghome.gmail.com](mailto:System_Monitor@bghome.gmail.com) and add "43" like this, restart gnome
> 
> "shell-version": [ "3.34", "3.32", "3.38", "40.0", "41", "42", "43"

I did not check the source.  I have created a [PR based](https://github.com/elvetemedve/gnome-shell-extension-system-monitor/pull/87) on your findings.  Thank you.

**Comment by elvetemedve** [comment]
An update has been released for this:
https://github.com/elvetemedve/gnome-shell-extension-system-monitor/releases/tag/25
