### ISSUE TITLE
Doesn't work on Ubuntu 16.04 with Gnome 3.18

### ISSUE THREAD

**Issue by kifetew** [elvetemedve/gnome-shell-extension-system-monitor#9]
I've tried to install it via the extension manager but the extension will not even show up in the list of gnome extensions. Then I tried to build it from source and install it. It installs, but is shown as disabled in the list of gnome extensions with a grey exclamation point in front of it. Any idea what could be the problem?
Thanks.

**Comment by elvetemedve** [comment]
Hi @kifetew,
The only external dependency in theory is **Libgtop** which has to be installed manually, see [installation guide](https://github.com/elvetemedve/gnome-shell-extension-system-monitor/wiki/Installation). Have you tried that?

**Comment by kifetew** [comment]
Thanks @elvetemedve, it works fine now. It turns out I missed the Libgtop dependency.
