### ISSUE TITLE
The popover stretches limitless outside the screen 

### ISSUE THREAD

**Issue by feimosi** [elvetemedve/gnome-shell-extension-system-monitor#97]
This has started happening after the recent update with GNOME 45 support. It looks like there's no maximum width, so for long process names it stretches without a limit. I have two Full HD screens and you can see the result below:

![Screenshot from 2023-12-12 23-26-14](https://github.com/elvetemedve/gnome-shell-extension-system-monitor/assets/5721520/849e41dd-8e8d-48d8-bb46-8285e5327e4c)

**Comment by elvetemedve** [comment]
Thanks for reporting this. You are right. The width of entries is not limited currently.
I will set a maximum limit.

**Comment by feimosi** [comment]
Appreciate it! Now it's fixed
